language: go

sudo: required

go:
  - "1.12.5"

dist: trusty

addons:
  postgresql: "9.6.6"

env:
  global:
    - DB_DRIVER=postgres
    - DB_NAME=gotest
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - DB_PORT=5432
    - GO111MODULE=on # enable Golang modules
    # NSQ message queue
    - NSQ_DOWNLOAD=nsq-1.1.0.linux-amd64.go1.10.3

services:
  - postgresql
  - redis-server

before_script:
  # restart redis
  - redis-cli shutdown
  - sudo redis-server --requirepass 'password' & echo "完成redis的启动"
  # restart postgres
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start
  # start postgres
  - psql -c 'create database gotest;' -U postgres

  # download nsq
  - wget http://bitly-downloads.s3.amazonaws.com/nsq/$NSQ_DOWNLOAD.tar.gz
  - tar zxvf $NSQ_DOWNLOAD.tar.gz
  - export PATH=$NSQ_DOWNLOAD/bin:$PATH
  - nsqlookupd
  - nsqd --lookupd-tcp-address=127.0.0.1:4160
  - nsqadmin --lookupd-http-address=127.0.0.1:4161

  - go get -v ./...

script:
  - make test
  - make build

after_success:
  # report code cover
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN