version: '3'
services:
  resource-api:
    image: alpine:3.11
    restart: always
    ports:
      - 9004:9004
    working_dir: /app
    volumes:
      - "./resource_server:/app/resource_server"
      - "./upload:/app/upload"
    environment:
      - MACHINE_ID=0
      - GO_MOD=development
    command: [ "./resource_server", "start" ]