name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        target: ['admin', 'user', 'resource', 'message_queue', 'scheduled', 'customer_service']
        kind: ['build']
        go: ['^1.15.0']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Go ${{ matrix.go }} ${{ matrix.kind }} ${{ matrix.target }} in ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env

      - name: Generate static bundle
        if: matrix.kind == 'build'
        env:
          GO111MODULE: off
        run: |
          go get github.com/markbates/pkger/cmd/pkger

      - name: Build ${{ matrix.target }}
        if: matrix.kind == 'build'
        run: |
          make generate-static
          bash ./scripts/build.sh ${{ matrix.target }}

      - uses: actions/upload-artifact@v2
        if: runner.os == 'linux'
        with:
          name: ${{ matrix.target }}
          path: ./bin/*.tar.gz

  lint:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        go: ['^1.15.0']
        os: [ubuntu-latest]
    name: Go ${{ matrix.go }} lint in ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env

      - name: Lint
        run: |
          GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.27.0
          go mod vendor
          golangci-lint --version
          make lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['^1.15.0']
        os: [ubuntu-latest]

    name: Go ${{ matrix.go }} test in ${{ matrix.os }}

    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: gotest
          POSTGRES_PASSWORD: gotest
          POSTGRES_DB: gotest
        ports:
          - 54321:5432
        # needed because the postgres container does not provide a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        # Docker Hub image
        image: redis:6.0.2-alpine
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      # 消息队列
      nsqlookupd:
        image: nsqio/nsq
        options: --entrypoint /nsqlookupd
        ports:
          - 4160:4160 # TCP 端口
          - 4161:4161 # HTTP 端口
      nsqd:
        image: nsqio/nsq
        options: --entrypoint /nsqd
        ports:
          - 4150:4150 # TCP 端口
          - 4151:4151 # HTTP 端口
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env

      - name: Test
        env:
          DB_DRIVER: postgres
          DB_NAME: gotest
          DB_USERNAME: gotest
          DB_PASSWORD: gotest
          DB_PORT: 54321
        run: |
          # 同步数据库
          go run cmd/admin/main.go migrate
          make test

      - name: Coverage
        if: github.repository == 'axetroy/go-server'
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          GO111MODULE=off go get golang.org/x/tools/cmd/cover
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service="GitHub Action" -jobid="${{ github.run_id }}" -jobnumber="${{ github.run_number }}" -reponame="${{ github.repository }}"

  release:
    name: Release to Github
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'axetroy/go-server'
    needs:  [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: user
          path: ./bin
      - uses: actions/download-artifact@v2
        with:
          name: admin
          path: ./bin
      - uses: actions/download-artifact@v2
        with:
          name: resource
          path: ./bin
      - uses: actions/download-artifact@v2
        with:
          name: message_queue
          path: ./bin
      - uses: actions/download-artifact@v2
        with:
          name: scheduled
          path: ./bin
      - uses: actions/download-artifact@v2
        with:
          name: customer_service
          path: ./bin

      - uses: softprops/action-gh-release@v1
        name: Release to Github
        env:
          # require Github Personal Access Token
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            ./bin/user_server_darwin_amd64.tar.gz
            ./bin/user_server_linux_amd64.tar.gz
            ./bin/user_server_windows_amd64.tar.gz
            ./bin/admin_server_darwin_amd64.tar.gz
            ./bin/admin_server_linux_amd64.tar.gz
            ./bin/admin_server_windows_amd64.tar.gz
            ./bin/resource_server_darwin_amd64.tar.gz
            ./bin/resource_server_linux_amd64.tar.gz
            ./bin/resource_server_windows_amd64.tar.gz
            ./bin/message_queue_server_darwin_amd64.tar.gz
            ./bin/message_queue_server_linux_amd64.tar.gz
            ./bin/message_queue_server_windows_amd64.tar.gz
            ./bin/scheduled_server_darwin_amd64.tar.gz
            ./bin/scheduled_server_linux_amd64.tar.gz
            ./bin/scheduled_server_windows_amd64.tar.gz
            ./bin/customer_service_server_darwin_amd64.tar.gz
            ./bin/customer_service_server_linux_amd64.tar.gz
            ./bin/customer_service_server_windows_amd64.tar.gz
          draft: false
